### ISSUE TITLE
Crash with aerospike server 3.8.2 with php client 3.4.8

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-server#126] opened 2016-05-05 18:44 UTC
Just execute the following code :

```php
<?php

$config = array("hosts" => array(array("addr" => "192.168.56.80", "port" => 3000)));
$db = new Aerospike($config, false);

$operations = array(
  array("op" => Aerospike::OP_LIST_INSERT, "bin" => "r", "val" => "value", "index" => -1),
  array("op" => Aerospike::OP_LIST_SIZE, "bin" => "r"),
);
$status = $db->operate($db->initKey("test", "test", "toto"), $operations, $ret_val);
````

The aerospike server crash :
````

May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:181) SIGSEGV received, aborting Aerospike Community Edition build 3.8.2 os ubuntu14.04
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: found 17 frames
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 0: /usr/bin/asd(as_sig_handle_segv+0x35) [0x48dacc]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 1: /lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f1ec30aad40]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 2: /lib/x86_64-linux-gnu/libc.so.6(memset+0x5d) [0x7f1ec310061d]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 3: /usr/bin/asd() [0x4830f9]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 4: /usr/bin/asd(cdt_process_state_packed_list_modify_optype+0x4c8) [0x4838f4]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 5: /usr/bin/asd(as_bin_cdt_packed_modify+0x82) [0x464f22]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 6: /usr/bin/asd(write_local_bin_ops_loop+0x75b) [0x4d3969]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 7: /usr/bin/asd(write_local_bin_ops+0xce) [0x4d3dea]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 8: /usr/bin/asd(write_local_dim+0x149) [0x4d4666]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 9: /usr/bin/asd(write_local+0x61c) [0x4d5a9a]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 10: /usr/bin/asd() [0x4da003]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 11: /usr/bin/asd(as_write_start+0x2a6) [0x4db801]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 12: /usr/bin/asd(process_transaction+0x431) [0x4e0589]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 13: /usr/bin/asd(thr_tsvc_process_or_enqueue+0xb1) [0x4e0c97]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 14: /usr/bin/asd(thr_demarshal+0xfb3) [0x4a8b23]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 15: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f1ec4286182]
May 05 2016 18:36:34 GMT: WARNING (as): (signal.c:185) stacktrace: frame 16: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f1ec316e47d]
````

**Comment by wchu-citrusleaf** [comment] 2016-05-05 19:34
Thanks. Will take a look.

**Comment by xorphox** [comment] 2016-05-06 01:45
Is the bin initially empty or did it have something in it?

**Comment by bpaquet** [comment] 2016-05-06 06:49
The record does not exists before.

**Comment by wchu-citrusleaf** [comment] 2016-05-19 16:47
Have found the issue to be PHP incorrectly converting -1 to a unsigned int. CLIENT-727 internally to fix client issue. The server also will protect against too large an index input. AER-4997

Thanks.

**Comment by aminer** [comment] 2016-05-25 15:06
The issue is fixed on the PHP Client.

**Closed** 2016-07-19 21:19 UTC
Labels: bug
