### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [aerospike/aerospike-server#24] opened 2021-03-11 13:13 UTC
[jw@cn06 aerospike-server]$ make VERBOSE=1 -j$(nproc)
mkdir -p ./target/Linux-aarch64/gen ./target/Linux-aarch64/lib ./target/Linux-aarch64/bin
mkdir -p ./target/Linux-aarch64/obj/base ./target/Linux-aarch64/obj/fabric ./target/Linux-aarch64/obj/storage ./target/Linux-aarch64/obj/geospatial ./target/Linux-aarch64/obj/transaction ./target/Linux-aarch64/obj/xdr
build/gen_version community fc33 > ./target/Linux-aarch64/gen/version.c
cc -o target/Linux-aarch64/obj/version.o -c target/Linux-aarch64/gen/version.c
make -C /home/jw/aerospike-server/modules/luajit Q= TARGET_SONAME=libluajit.so CCDEBUG=-g
make[1]: Entering directory '/home/jw/aerospike-server/modules/luajit'
==== Building LuaJIT 2.0.3 ====
make -C src
make[2]: Entering directory '/home/jw/aerospike-server/modules/luajit/src'
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:279:2: error: #error "No target architecture defined"
  279 | #error "No target architecture defined"
      |  ^~~~~
Makefile:231: *** Unsupported target architecture.  Stop.
make[2]: Leaving directory '/home/jw/aerospike-server/modules/luajit/src'
make[1]: *** [Makefile:104: default] Error 2
make[1]: Leaving directory '/home/jw/aerospike-server/modules/luajit'
make: *** [Makefile:54: aslibs] Error 2
[jw@cn06 aerospike-server]$ 

Note, luajit-devel is installed.

**Comment by kportertx** [comment] 2021-03-11 17:50
Duplicate of https://github.com/aerospike/aerospike-server/issues/19.

**Closed as completed by kportertx** 2021-03-11 17:50 UTC
