### ISSUE TITLE
epoll_event isn't packed on all architectures

### ISSUE THREAD

**Issue by grooverdan** [aerospike/aerospike-server#3] opened 2018-05-22 03:25 UTC
ubuntu-18.04 ppc64le - git master @ c302133

epoll_event isn't packed on all architectures so replicating the structure isn't portable and indeed causes runtime ppc64le problems.

The structure is redefined here:
https://github.com/aerospike/aerospike-server/blob/master/cf/include/socket.h#L156..L160

For portability the data.ptr union element could be used where the existing code rather than recreating the structure data structure element.

The structure is defined in the standard:
https://linux.die.net/man/2/epoll_wait

**Comment by grooverdan** [comment] 2021-09-02 04:38
:snail:

**Comment by kportertx** [comment] 2022-09-12 02:13
This will be addressed in 6.2 to support ARM. This ticket is now effectively a duplicate of #19.

**Closed as completed** 2022-09-12 02:13 UTC
Labels: Priority: Low, Type: Feature Request, Component: Build

**Comment by kportertx** [comment] 2022-11-19 04:40
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0
